spin_manifest_version = 2

[application]
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = "QR Code generator for Spin"
name = "spin-qr-generator"
version = "0.0.2"

[variables]
qr_url = { default = "" }

[[trigger.http]]
route = "/..."
component = "spin-qr-generator"

[component.spin-qr-generator]
source = "qr-generator/target/wasm32-wasi/release/spin_qr_generator.wasm"
[component.spin-qr-generator.variables]
qr_url = "{{ qr_url }}"
[component.spin-qr-generator.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "qr-generator"
