spin_manifest_version = "1"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = "QR Code generator for Spin"
name = "spin-qr-generator"
trigger = { type = "http", base = "/" }
version = "0.0.1"

[[component]]
id = "spin-qr-generator"
source = { url = "https://github.com/mikkelhegn/spin-qr-generator/releases/download/v0.0.2/spin_qr_generator.wasm", digest = "sha256:8c9a1de8370caecd33d34d2ec8c0d142619fc4aee5dd85d87b0afcb944b69873" }
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "qr-generator"
