spin_manifest_version = "1"
authors = ["Mikkel Mørk Hegnhøj <mikkel@fermyon.com>"]
description = "QR Code generator for Spin"
name = "spin-qr-generator"
trigger = { type = "http", base = "/" }
version = "0.0.1"

[[component]]
id = "spin-qr-generator"
source = "qr-generator/target/wasm32-wasi/release/spin_qr_generator.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "qr-generator"
